// قاعدة بيانات الجرد التراكمي الشامل للموسم (2025-2026)
const SEASONAL_INVENTORY_DATA = [
  {
    "id": 1,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب القول الفصل",
    "councilNumber": 1,
    "title": "شرح كتاب القول الفصل - المجلس (01)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 2,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب القول الفصل",
    "councilNumber": 2,
    "title": "شرح كتاب القول الفصل - المجلس (02)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 3,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب القول الفصل",
    "councilNumber": 3,
    "title": "شرح كتاب القول الفصل - المجلس (03)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 4,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب القول الفصل",
    "councilNumber": 4,
    "title": "شرح كتاب القول الفصل - المجلس (04)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 5,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب القول الفصل",
    "councilNumber": 5,
    "title": "شرح كتاب القول الفصل - المجلس (05)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 6,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب القول الفصل",
    "councilNumber": 6,
    "title": "شرح كتاب القول الفصل - المجلس (06)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 7,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب القول الفصل",
    "councilNumber": 7,
    "title": "شرح كتاب القول الفصل - المجلس (07)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 8,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب القول الفصل",
    "councilNumber": 8,
    "title": "شرح كتاب القول الفصل - المجلس (08)",
    "instructor": "أ.د عمار جيدل",
    "status": "IN_MONTAGE",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 9,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب القول الفصل",
    "councilNumber": 9,
    "title": "شرح كتاب القول الفصل - المجلس (09)",
    "instructor": "أ.د عمار جيدل",
    "status": "IN_MONTAGE",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 10,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب القول الفصل",
    "councilNumber": 10,
    "title": "شرح كتاب القول الفصل - المجلس (10)",
    "instructor": "أ.د عمار جيدل",
    "status": "IN_MONTAGE",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 11,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب القول الفصل",
    "councilNumber": 11,
    "title": "شرح كتاب القول الفصل - المجلس (11)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 12,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب القول الفصل",
    "councilNumber": 12,
    "title": "شرح كتاب القول الفصل - المجلس (12)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 13,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب القول الفصل",
    "councilNumber": 13,
    "title": "شرح كتاب القول الفصل - المجلس (13)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 14,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب القول الفصل",
    "councilNumber": 14,
    "title": "شرح كتاب القول الفصل - المجلس (14)",
    "instructor": "أ.د عمار جيدل",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=0dSE7ErZm7U",
    "views": 149,
    "publishedDate": "2025-11-28"
  },
  {
    "id": 15,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب القول الفصل",
    "councilNumber": 15,
    "title": "شرح كتاب القول الفصل - المجلس (15)",
    "instructor": "أ.د عمار جيدل",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=8nc3oiiqZtw",
    "views": 174,
    "publishedDate": "2025-12-03"
  },
  {
    "id": 16,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب القول الفصل",
    "councilNumber": 16,
    "title": "شرح كتاب القول الفصل - المجلس (16)",
    "instructor": "أ.د عمار جيدل",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=2-AKPiVCMss",
    "views": 279,
    "publishedDate": "2026-07-29"
  },
  {
    "id": 17,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب القول الفصل",
    "councilNumber": 17,
    "title": "شرح كتاب القول الفصل - المجلس (17)",
    "instructor": "أ.د عمار جيدل",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=0tU8d6XtdFY",
    "views": 172,
    "publishedDate": "2026-08-08"
  },
  {
    "id": 18,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب القول الفصل",
    "councilNumber": 18,
    "title": "شرح كتاب القول الفصل - المجلس (18)",
    "instructor": "أ.د عمار جيدل",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=BEE4-O1pQHk",
    "views": 169,
    "publishedDate": "2026-08-14"
  },
  {
    "id": 19,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب القول الفصل",
    "councilNumber": 19,
    "title": "شرح كتاب القول الفصل - المجلس (19)",
    "instructor": "أ.د عمار جيدل",
    "status": "IN_MONTAGE",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 20,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب القول الفصل",
    "councilNumber": 20,
    "title": "شرح كتاب القول الفصل - المجلس (20)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 21,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح المنظومة البيقونية",
    "councilNumber": 1,
    "title": "شرح المنظومة البيقونية - المجلس (01)",
    "instructor": "د. حسن بنونة",
    "status": "IN_MONTAGE",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 22,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح المنظومة البيقونية",
    "councilNumber": 2,
    "title": "شرح المنظومة البيقونية - المجلس (02)",
    "instructor": "د. حسن بنونة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 23,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح المنظومة البيقونية",
    "councilNumber": 3,
    "title": "شرح المنظومة البيقونية - المجلس (03)",
    "instructor": "د. حسن بنونة",
    "status": "IN_MONTAGE",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 24,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح المنظومة البيقونية",
    "councilNumber": 4,
    "title": "شرح المنظومة البيقونية - المجلس (04)",
    "instructor": "د. حسن بنونة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 25,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح المنظومة البيقونية",
    "councilNumber": 5,
    "title": "شرح المنظومة البيقونية - المجلس (05)",
    "instructor": "د. حسن بنونة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 26,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح المنظومة البيقونية",
    "councilNumber": 6,
    "title": "شرح المنظومة البيقونية - المجلس (06)",
    "instructor": "د. حسن بنونة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 27,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح المنظومة البيقونية",
    "councilNumber": 7,
    "title": "شرح المنظومة البيقونية - المجلس (07)",
    "instructor": "د. حسن بنونة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 28,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح المنظومة البيقونية",
    "councilNumber": 8,
    "title": "شرح المنظومة البيقونية - المجلس (08)",
    "instructor": "د. حسن بنونة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 29,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح المنظومة البيقونية",
    "councilNumber": 9,
    "title": "شرح المنظومة البيقونية - المجلس (09)",
    "instructor": "د. حسن بنونة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 30,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح المنظومة البيقونية",
    "councilNumber": 10,
    "title": "شرح المنظومة البيقونية - المجلس (10)",
    "instructor": "د. حسن بنونة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 31,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح المنظومة البيقونية",
    "councilNumber": 11,
    "title": "شرح المنظومة البيقونية - المجلس (11)",
    "instructor": "د. حسن بنونة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 32,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح المنظومة البيقونية",
    "councilNumber": 12,
    "title": "شرح المنظومة البيقونية - المجلس (12)",
    "instructor": "د. حسن بنونة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 33,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح المنظومة البيقونية",
    "councilNumber": 13,
    "title": "شرح المنظومة البيقونية - المجلس (13)",
    "instructor": "د. حسن بنونة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 34,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح المنظومة البيقونية",
    "councilNumber": 14,
    "title": "شرح المنظومة البيقونية - المجلس (14)",
    "instructor": "د. حسن بنونة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 35,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "دورة التفكير النقدي",
    "councilNumber": 1,
    "title": "دورة التفكير النقدي - المجلس (01)",
    "instructor": "د. محمد لمين إبراقن",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 36,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "دورة التفكير النقدي",
    "councilNumber": 2,
    "title": "دورة التفكير النقدي - المجلس (02)",
    "instructor": "د. محمد لمين إبراقن",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 37,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "دورة التفكير النقدي",
    "councilNumber": 3,
    "title": "دورة التفكير النقدي - المجلس (03)",
    "instructor": "د. محمد لمين إبراقن",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 38,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "دورة التفكير النقدي",
    "councilNumber": 4,
    "title": "دورة التفكير النقدي - المجلس (04)",
    "instructor": "د. محمد لمين إبراقن",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 39,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "دورة التفكير النقدي",
    "councilNumber": 5,
    "title": "دورة التفكير النقدي - المجلس (05)",
    "instructor": "د. محمد لمين إبراقن",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 40,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "دورة التفكير النقدي",
    "councilNumber": 6,
    "title": "دورة التفكير النقدي - المجلس (06)",
    "instructor": "د. محمد لمين إبراقن",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 41,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "دورة التفكير النقدي",
    "councilNumber": 7,
    "title": "دورة التفكير النقدي - المجلس (07)",
    "instructor": "د. محمد لمين إبراقن",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 42,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "دورة التفكير النقدي",
    "councilNumber": 8,
    "title": "دورة التفكير النقدي - المجلس (08)",
    "instructor": "د. محمد لمين إبراقن",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 43,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "دورة التفكير النقدي",
    "councilNumber": 9,
    "title": "دورة التفكير النقدي - المجلس (09)",
    "instructor": "د. محمد لمين إبراقن",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 44,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "دورة التفكير النقدي",
    "councilNumber": 10,
    "title": "دورة التفكير النقدي - المجلس (10)",
    "instructor": "د. محمد لمين إبراقن",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 45,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "دورة التفكير النقدي",
    "councilNumber": 11,
    "title": "دورة التفكير النقدي - المجلس (11)",
    "instructor": "د. محمد لمين إبراقن",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 46,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "دورة التفكير النقدي",
    "councilNumber": 12,
    "title": "دورة التفكير النقدي - المجلس (12)",
    "instructor": "د. محمد لمين إبراقن",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 47,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التزكية والرقائق",
    "councilNumber": 1,
    "title": "مجالس التزكية والرقائق - المجلس (01)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 48,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التزكية والرقائق",
    "councilNumber": 2,
    "title": "مجالس التزكية والرقائق - المجلس (02)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 49,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التزكية والرقائق",
    "councilNumber": 3,
    "title": "مجالس التزكية والرقائق - المجلس (03)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 50,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التزكية والرقائق",
    "councilNumber": 4,
    "title": "مجالس التزكية والرقائق - المجلس (04)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 51,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التزكية والرقائق",
    "councilNumber": 5,
    "title": "مجالس التزكية والرقائق - المجلس (05)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 52,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التزكية والرقائق",
    "councilNumber": 6,
    "title": "مجالس التزكية والرقائق - المجلس (06)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 53,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التزكية والرقائق",
    "councilNumber": 7,
    "title": "مجالس التزكية والرقائق - المجلس (07)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 54,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التزكية والرقائق",
    "councilNumber": 8,
    "title": "مجالس التزكية والرقائق - المجلس (08)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 55,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التزكية والرقائق",
    "councilNumber": 9,
    "title": "مجالس التزكية والرقائق - المجلس (09)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 56,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التزكية والرقائق",
    "councilNumber": 10,
    "title": "مجالس التزكية والرقائق - المجلس (10)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 57,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التزكية والرقائق",
    "councilNumber": 11,
    "title": "مجالس التزكية والرقائق - المجلس (11)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 58,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التزكية والرقائق",
    "councilNumber": 12,
    "title": "مجالس التزكية والرقائق - المجلس (12)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 59,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 1,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (01)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 60,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 2,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (02)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 61,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 3,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (03)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 62,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 4,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (04)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 63,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 5,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (05)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 64,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 6,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (06)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 65,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 7,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (07)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 66,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 8,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (08)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 67,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 9,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (09)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 68,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 10,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (10)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 69,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 11,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (11)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 70,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 12,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (12)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 71,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 13,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (13)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 72,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 14,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (14)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 73,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 15,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (15)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 74,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 16,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (16)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 75,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 17,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (17)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 76,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 18,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (18)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 77,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 19,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (19)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 78,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 20,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (20)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 79,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 21,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (21)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 80,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 22,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (22)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 81,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 23,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (23)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 82,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 24,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (24)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 83,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة بناء الطالب الرسالي",
    "councilNumber": 25,
    "title": "سلسلة بناء الطالب الرسالي - المجلس (25)",
    "instructor": "د. دليلة قيراد",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 84,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب الموقف وعلم الكلام",
    "councilNumber": 1,
    "title": "شرح كتاب الموقف وعلم الكلام - المجلس (01)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 85,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب الموقف وعلم الكلام",
    "councilNumber": 2,
    "title": "شرح كتاب الموقف وعلم الكلام - المجلس (02)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 86,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب الموقف وعلم الكلام",
    "councilNumber": 3,
    "title": "شرح كتاب الموقف وعلم الكلام - المجلس (03)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 87,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب الموقف وعلم الكلام",
    "councilNumber": 4,
    "title": "شرح كتاب الموقف وعلم الكلام - المجلس (04)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 88,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب الموقف وعلم الكلام",
    "councilNumber": 5,
    "title": "شرح كتاب الموقف وعلم الكلام - المجلس (05)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 89,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب الموقف وعلم الكلام",
    "councilNumber": 6,
    "title": "شرح كتاب الموقف وعلم الكلام - المجلس (06)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 90,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب الموقف وعلم الكلام",
    "councilNumber": 7,
    "title": "شرح كتاب الموقف وعلم الكلام - المجلس (07)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 91,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب الموقف وعلم الكلام",
    "councilNumber": 8,
    "title": "شرح كتاب الموقف وعلم الكلام - المجلس (08)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 92,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب الموقف وعلم الكلام",
    "councilNumber": 9,
    "title": "شرح كتاب الموقف وعلم الكلام - المجلس (09)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 93,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح كتاب الموقف وعلم الكلام",
    "councilNumber": 10,
    "title": "شرح كتاب الموقف وعلم الكلام - المجلس (10)",
    "instructor": "أ.د عمار جيدل",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 94,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح العقيدة الطحاوية ومدارج السالكين",
    "councilNumber": 1,
    "title": "شرح العقيدة الطحاوية ومدارج السالكين - المجلس (01)",
    "instructor": "مشايخ وأساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 95,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح العقيدة الطحاوية ومدارج السالكين",
    "councilNumber": 2,
    "title": "شرح العقيدة الطحاوية ومدارج السالكين - المجلس (02)",
    "instructor": "مشايخ وأساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 96,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح العقيدة الطحاوية ومدارج السالكين",
    "councilNumber": 3,
    "title": "شرح العقيدة الطحاوية ومدارج السالكين - المجلس (03)",
    "instructor": "مشايخ وأساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 97,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح العقيدة الطحاوية ومدارج السالكين",
    "councilNumber": 4,
    "title": "شرح العقيدة الطحاوية ومدارج السالكين - المجلس (04)",
    "instructor": "مشايخ وأساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 98,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح العقيدة الطحاوية ومدارج السالكين",
    "councilNumber": 5,
    "title": "شرح العقيدة الطحاوية ومدارج السالكين - المجلس (05)",
    "instructor": "مشايخ وأساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 99,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح العقيدة الطحاوية ومدارج السالكين",
    "councilNumber": 6,
    "title": "شرح العقيدة الطحاوية ومدارج السالكين - المجلس (06)",
    "instructor": "مشايخ وأساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 100,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح العقيدة الطحاوية ومدارج السالكين",
    "councilNumber": 7,
    "title": "شرح العقيدة الطحاوية ومدارج السالكين - المجلس (07)",
    "instructor": "مشايخ وأساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 101,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح العقيدة الطحاوية ومدارج السالكين",
    "councilNumber": 8,
    "title": "شرح العقيدة الطحاوية ومدارج السالكين - المجلس (08)",
    "instructor": "مشايخ وأساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 102,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح العقيدة الطحاوية ومدارج السالكين",
    "councilNumber": 9,
    "title": "شرح العقيدة الطحاوية ومدارج السالكين - المجلس (09)",
    "instructor": "مشايخ وأساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 103,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح العقيدة الطحاوية ومدارج السالكين",
    "councilNumber": 10,
    "title": "شرح العقيدة الطحاوية ومدارج السالكين - المجلس (10)",
    "instructor": "مشايخ وأساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 104,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح العقيدة الطحاوية ومدارج السالكين",
    "councilNumber": 11,
    "title": "شرح العقيدة الطحاوية ومدارج السالكين - المجلس (11)",
    "instructor": "مشايخ وأساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 105,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح العقيدة الطحاوية ومدارج السالكين",
    "councilNumber": 12,
    "title": "شرح العقيدة الطحاوية ومدارج السالكين - المجلس (12)",
    "instructor": "مشايخ وأساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 106,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح العقيدة الطحاوية ومدارج السالكين",
    "councilNumber": 13,
    "title": "شرح العقيدة الطحاوية ومدارج السالكين - المجلس (13)",
    "instructor": "مشايخ وأساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 107,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح العقيدة الطحاوية ومدارج السالكين",
    "councilNumber": 14,
    "title": "شرح العقيدة الطحاوية ومدارج السالكين - المجلس (14)",
    "instructor": "مشايخ وأساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 108,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "شرح العقيدة الطحاوية ومدارج السالكين",
    "councilNumber": 15,
    "title": "شرح العقيدة الطحاوية ومدارج السالكين - المجلس (15)",
    "instructor": "مشايخ وأساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 109,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التأصيل في علوم الآلة والمنطق",
    "councilNumber": 1,
    "title": "مجالس التأصيل في علوم الآلة والمنطق - المجلس (01)",
    "instructor": "أساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 110,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التأصيل في علوم الآلة والمنطق",
    "councilNumber": 2,
    "title": "مجالس التأصيل في علوم الآلة والمنطق - المجلس (02)",
    "instructor": "أساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 111,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التأصيل في علوم الآلة والمنطق",
    "councilNumber": 3,
    "title": "مجالس التأصيل في علوم الآلة والمنطق - المجلس (03)",
    "instructor": "أساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 112,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التأصيل في علوم الآلة والمنطق",
    "councilNumber": 4,
    "title": "مجالس التأصيل في علوم الآلة والمنطق - المجلس (04)",
    "instructor": "أساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 113,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التأصيل في علوم الآلة والمنطق",
    "councilNumber": 5,
    "title": "مجالس التأصيل في علوم الآلة والمنطق - المجلس (05)",
    "instructor": "أساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 114,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التأصيل في علوم الآلة والمنطق",
    "councilNumber": 6,
    "title": "مجالس التأصيل في علوم الآلة والمنطق - المجلس (06)",
    "instructor": "أساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 115,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التأصيل في علوم الآلة والمنطق",
    "councilNumber": 7,
    "title": "مجالس التأصيل في علوم الآلة والمنطق - المجلس (07)",
    "instructor": "أساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 116,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التأصيل في علوم الآلة والمنطق",
    "councilNumber": 8,
    "title": "مجالس التأصيل في علوم الآلة والمنطق - المجلس (08)",
    "instructor": "أساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 117,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التأصيل في علوم الآلة والمنطق",
    "councilNumber": 9,
    "title": "مجالس التأصيل في علوم الآلة والمنطق - المجلس (09)",
    "instructor": "أساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 118,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التأصيل في علوم الآلة والمنطق",
    "councilNumber": 10,
    "title": "مجالس التأصيل في علوم الآلة والمنطق - المجلس (10)",
    "instructor": "أساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 119,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التأصيل في علوم الآلة والمنطق",
    "councilNumber": 11,
    "title": "مجالس التأصيل في علوم الآلة والمنطق - المجلس (11)",
    "instructor": "أساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 120,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التأصيل في علوم الآلة والمنطق",
    "councilNumber": 12,
    "title": "مجالس التأصيل في علوم الآلة والمنطق - المجلس (12)",
    "instructor": "أساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 121,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التأصيل في علوم الآلة والمنطق",
    "councilNumber": 13,
    "title": "مجالس التأصيل في علوم الآلة والمنطق - المجلس (13)",
    "instructor": "أساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 122,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التأصيل في علوم الآلة والمنطق",
    "councilNumber": 14,
    "title": "مجالس التأصيل في علوم الآلة والمنطق - المجلس (14)",
    "instructor": "أساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 123,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التأصيل في علوم الآلة والمنطق",
    "councilNumber": 15,
    "title": "مجالس التأصيل في علوم الآلة والمنطق - المجلس (15)",
    "instructor": "أساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 124,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "مجالس التأصيل في علوم الآلة والمنطق",
    "councilNumber": 16,
    "title": "مجالس التأصيل في علوم الآلة والمنطق - المجلس (16)",
    "instructor": "أساتذة النادي",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 125,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة)",
    "councilNumber": 1,
    "title": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة) - المجلس (01)",
    "instructor": "نخبة من الدكاترة والباحثين",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 126,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة)",
    "councilNumber": 2,
    "title": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة) - المجلس (02)",
    "instructor": "نخبة من الدكاترة والباحثين",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 127,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة)",
    "councilNumber": 3,
    "title": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة) - المجلس (03)",
    "instructor": "نخبة من الدكاترة والباحثين",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 128,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة)",
    "councilNumber": 4,
    "title": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة) - المجلس (04)",
    "instructor": "نخبة من الدكاترة والباحثين",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 129,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة)",
    "councilNumber": 5,
    "title": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة) - المجلس (05)",
    "instructor": "نخبة من الدكاترة والباحثين",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 130,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة)",
    "councilNumber": 6,
    "title": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة) - المجلس (06)",
    "instructor": "نخبة من الدكاترة والباحثين",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 131,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة)",
    "councilNumber": 7,
    "title": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة) - المجلس (07)",
    "instructor": "نخبة من الدكاترة والباحثين",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 132,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة)",
    "councilNumber": 8,
    "title": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة) - المجلس (08)",
    "instructor": "نخبة من الدكاترة والباحثين",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 133,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة)",
    "councilNumber": 9,
    "title": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة) - المجلس (09)",
    "instructor": "نخبة من الدكاترة والباحثين",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 134,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة)",
    "councilNumber": 10,
    "title": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة) - المجلس (10)",
    "instructor": "نخبة من الدكاترة والباحثين",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 135,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة)",
    "councilNumber": 11,
    "title": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة) - المجلس (11)",
    "instructor": "نخبة من الدكاترة والباحثين",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 136,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة)",
    "councilNumber": 12,
    "title": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة) - المجلس (12)",
    "instructor": "نخبة من الدكاترة والباحثين",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 137,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة)",
    "councilNumber": 13,
    "title": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة) - المجلس (13)",
    "instructor": "نخبة من الدكاترة والباحثين",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 138,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة)",
    "councilNumber": 14,
    "title": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة) - المجلس (14)",
    "instructor": "نخبة من الدكاترة والباحثين",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 139,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة)",
    "councilNumber": 15,
    "title": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة) - المجلس (15)",
    "instructor": "نخبة من الدكاترة والباحثين",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 140,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة)",
    "councilNumber": 16,
    "title": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة) - المجلس (16)",
    "instructor": "نخبة من الدكاترة والباحثين",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 141,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة)",
    "councilNumber": 17,
    "title": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة) - المجلس (17)",
    "instructor": "نخبة من الدكاترة والباحثين",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 142,
    "category": "council",
    "categoryLabel": "📚 مجلس علمي / دورة",
    "series": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة)",
    "councilNumber": 18,
    "title": "سلسلة نحو أفق الفكر والمعرفة (المجالس العامة) - المجلس (18)",
    "instructor": "نخبة من الدكاترة والباحثين",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 143,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 1,
    "title": "مناقشة ماستر | شبهات المستشرقة كارن باور حول آيات المرأة والنسوية",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=uJUjHugU254",
    "views": 585,
    "publishedDate": "2026-08-01"
  },
  {
    "id": 144,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 2,
    "title": "مناقشة ماستر | التعليل الفقهي عند القاضي عبد الوهاب المالكي",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=GQ3shTjjhwU",
    "views": 688,
    "publishedDate": "2026-07-23"
  },
  {
    "id": 145,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 3,
    "title": "مناقشة ماستر | مقاصد ختم الآيات بأسماء الله الحسنى",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=6hKy38dM6BY",
    "views": 444,
    "publishedDate": "2026-07-26"
  },
  {
    "id": 146,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 4,
    "title": "مناقشة ماستر | عصمة الأنبياء في الفكر الإسلامي المعاصر",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=FyBi83gzhAo",
    "views": 2980,
    "publishedDate": "2026-07-20"
  },
  {
    "id": 147,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 5,
    "title": "مناقشة ماستر | الترشيد في التصرفات المالية وتطبيقاته المعاصرة",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=GQ3shTjjhwU",
    "views": 688,
    "publishedDate": "2026-07-23"
  },
  {
    "id": 148,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 6,
    "title": "مناقشة ماستر | العلاقات التاريخية بين المغاربة وبيت المقدس",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=XE1V76ihgM4",
    "views": 666,
    "publishedDate": "2026-07-30"
  },
  {
    "id": 149,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 7,
    "title": "مناقشة ماستر | مشكلة الشر بين الفلسفة وعلم الكلام",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=g9Yq1DEAsS4",
    "views": 140,
    "publishedDate": "2026-05-26"
  },
  {
    "id": 150,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 8,
    "title": "مناقشة ماستر | المنهج النبوي في حراسة النصوص المقدسة",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=fAuICWbN3lM",
    "views": 205,
    "publishedDate": "2026-02-12"
  },
  {
    "id": 151,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 9,
    "title": "مناقشة ماستر | معجزات المسيح بين القرآن والأناجيل",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=6hKy38dM6BY",
    "views": 444,
    "publishedDate": "2026-07-26"
  },
  {
    "id": 152,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 10,
    "title": "مناقشة ماستر | الأحوال والمقامات عند الإمام المحاسبي",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=6bIC37Pdzsw",
    "views": 478,
    "publishedDate": "2026-08-06"
  },
  {
    "id": 153,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 11,
    "title": "مناقشة ماستر | آراء ابن عبد البر التحديثية والفقهية",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 154,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 12,
    "title": "مناقشة ماستر | مناهج الاستدلال العقدي عند الأشاعرة",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=0yBIYq6BFXY",
    "views": 985,
    "publishedDate": "2026-07-25"
  },
  {
    "id": 155,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 13,
    "title": "مناقشة الدكتوراه: ضمانات حقوق الإنسان في الإسلام",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=6bIC37Pdzsw",
    "views": 478,
    "publishedDate": "2026-08-06"
  },
  {
    "id": 156,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 14,
    "title": "مناقشة ماستر | التربية الروحية عند الأمير عبد القادر",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=golS2_agzHU",
    "views": 70,
    "publishedDate": "2026-04-24"
  },
  {
    "id": 157,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 15,
    "title": "مناقشة ماستر | أدلة وجود الله عند الشيخ محمد عبد الله دراز",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=iC1vL8K2NJ8",
    "views": 684,
    "publishedDate": "2026-08-09"
  },
  {
    "id": 158,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 16,
    "title": "مناقشة ماستر | إتجاهات التجديد في علم الكلام الجزائري",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 159,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 17,
    "title": "مناقشة ماستر | المشاريع الإعلامية في خدمة القرآن الكريم",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=6hKy38dM6BY",
    "views": 444,
    "publishedDate": "2026-07-26"
  },
  {
    "id": 160,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 18,
    "title": "مناقشة ماستر | قضايا العقيدة في تفسير المنار",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=6hKy38dM6BY",
    "views": 444,
    "publishedDate": "2026-07-26"
  },
  {
    "id": 161,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 19,
    "title": "مناقشة ماستر | نظرية الغرر في العقود المالية عند الإباضية",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=v5TdIPyPDas",
    "views": 419,
    "publishedDate": "2026-07-09"
  },
  {
    "id": 162,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 20,
    "title": "مناقشة ماستر | الذكاء الاصطناعي بين التحيز والموضوعية الأخلاقية",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 163,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 21,
    "title": "مناقشة ماستر | الروايات التاريخية التي يستشهد بها الشيعة في القرنين 1 و 2",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=XE1V76ihgM4",
    "views": 666,
    "publishedDate": "2026-07-30"
  },
  {
    "id": 164,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 22,
    "title": "مناقشة ماستر | مناهج المحدثين في تعليل الروايات",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=XE1V76ihgM4",
    "views": 666,
    "publishedDate": "2026-07-30"
  },
  {
    "id": 165,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 23,
    "title": "مناقشة ماستر | التأويل العقدي عند الماتريدية",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=0yBIYq6BFXY",
    "views": 985,
    "publishedDate": "2026-07-25"
  },
  {
    "id": 166,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 24,
    "title": "مناقشة ماستر | الحرية السياسية في الفكر الإسلامي المعاصر",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=FyBi83gzhAo",
    "views": 2980,
    "publishedDate": "2026-07-20"
  },
  {
    "id": 167,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 25,
    "title": "مناقشة ماستر | الإعجاز البياني في سورة النمل",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=0yBIYq6BFXY",
    "views": 985,
    "publishedDate": "2026-07-25"
  },
  {
    "id": 168,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 26,
    "title": "مناقشة ماستر | النقد الحداثي للسنة النبوية (دراسة تقويمية)",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=iC1vL8K2NJ8",
    "views": 684,
    "publishedDate": "2026-08-09"
  },
  {
    "id": 169,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 27,
    "title": "مناقشة ماستر | التوجيه المقاصدي للفتوى المعاصرة",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 170,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 28,
    "title": "مناقشة ماستر | أصول الفقه عند الشوكاني من خلال نيل الأوطار",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=6hKy38dM6BY",
    "views": 444,
    "publishedDate": "2026-07-26"
  },
  {
    "id": 171,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 29,
    "title": "مناقشة ماستر | المصطلح الصوفي عند عبد القادر الجيلاني",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 172,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 30,
    "title": "مناقشة ماستر | أثر المقاصد الشرعية في فقه المعاملات المالية",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 173,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 31,
    "title": "مناقشة ماستر | مناهج المفسرين الجزائريين في القرن العشرين",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=XE1V76ihgM4",
    "views": 666,
    "publishedDate": "2026-07-30"
  },
  {
    "id": 174,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 32,
    "title": "مناقشة ماستر | شبهات الاستشراق الألماني حول القرآن",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=uJUjHugU254",
    "views": 585,
    "publishedDate": "2026-08-01"
  },
  {
    "id": 175,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 33,
    "title": "مناقشة ماستر | فلسفة الأخلاق عند ابن مسكويه",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 176,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 34,
    "title": "مناقشة ماستر | الحوار الديني في الحضارة الأندلسية",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=cXab3lbAP_g",
    "views": 528,
    "publishedDate": "2026-07-13"
  },
  {
    "id": 177,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 35,
    "title": "مناقشة ماستر | القيم التربوية في السيرة النبوية",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 178,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 36,
    "title": "مناقشة ماستر | الدراسات الاستشراقية للسيرة النبوية",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 179,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 37,
    "title": "مناقشة ماستر | التجديد الأصولي عند الشيخ الطاهر بن عاشور",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=FjVqE2qrsUI",
    "views": 788,
    "publishedDate": "2026-07-15"
  },
  {
    "id": 180,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 38,
    "title": "مناقشة ماستر | الموقف من المنطق الأرسطي في الفكر الإسلامي",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=FyBi83gzhAo",
    "views": 2980,
    "publishedDate": "2026-07-20"
  },
  {
    "id": 181,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 39,
    "title": "مناقشة ماستر | نظرية المعرفة عند الإمام الغزالي",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=6bIC37Pdzsw",
    "views": 478,
    "publishedDate": "2026-08-06"
  },
  {
    "id": 182,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 40,
    "title": "مناقشة ماستر | فقه الأولويات وتطبيقاته في العمل الدعوي",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=GQ3shTjjhwU",
    "views": 688,
    "publishedDate": "2026-07-23"
  },
  {
    "id": 183,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 41,
    "title": "مناقشة ماستر | مناهج الاستدلال بالسنة عند المالكية",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "PUBLISHED",
    "videoUrl": "https://www.youtube.com/watch?v=DbrUgQV1Krc",
    "views": 3015,
    "publishedDate": "2026-06-30"
  },
  {
    "id": 184,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه",
    "councilNumber": 42,
    "title": "مناقشة ماستر | الفلسفة السياسية عند الفارابي",
    "instructor": "باحث / باحثة (لجنة المناقشة)",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 185,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 43,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (43)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 186,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 44,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (44)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 187,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 45,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (45)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 188,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 46,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (46)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 189,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 47,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (47)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 190,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 48,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (48)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 191,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 49,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (49)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 192,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 50,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (50)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 193,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 51,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (51)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 194,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 52,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (52)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 195,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 53,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (53)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 196,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 54,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (54)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 197,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 55,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (55)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 198,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 56,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (56)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 199,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 57,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (57)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 200,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 58,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (58)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 201,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 59,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (59)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 202,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 60,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (60)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 203,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 61,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (61)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 204,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 62,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (62)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 205,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 63,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (63)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 206,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 64,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (64)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 207,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 65,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (65)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 208,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 66,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (66)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 209,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 67,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (67)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 210,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 68,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (68)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 211,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 69,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (69)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 212,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 70,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (70)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 213,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 71,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (71)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 214,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 72,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (72)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 215,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 73,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (73)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 216,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 74,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (74)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 217,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 75,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (75)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 218,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 76,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (76)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 219,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 77,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (77)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 220,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 78,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (78)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  },
  {
    "id": 221,
    "category": "discussion",
    "categoryLabel": "🎓 مناقشة علمية (ماستر/دكتوراه)",
    "series": "مناقشات الماستر والدكتوراه (أرشيف التسجيلات الخام)",
    "councilNumber": 79,
    "title": "مناقشة ماستر/دكتوراه - التسجيل الخام رقم (79)",
    "instructor": "باحث / باحثة",
    "status": "UNMONTAGED",
    "videoUrl": "",
    "views": 0,
    "publishedDate": ""
  }
];
